# Generated by Django 5.0.2 on 2024-02-19 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
