# Generated by Django 5.0.2 on 2024-02-20 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_order_paid_order_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='additional_info',
        ),
    ]
