# Generated by Django 5.0.2 on 2024-02-20 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_order_additional_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='contry',
            new_name='country',
        ),
    ]
